ARG SERVERCORE_VERSION

FROM mcr.microsoft.com/windows/servercore:${SERVERCORE_VERSION}
SHELL ["powershell", "-NoLogo", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue';"]

COPY tests/integration/bin/nginx.zip /nginx.zip
RUN Write-Host 'Expanding ...'; \
    Expand-Archive -Force -Path c:\nginx.zip -DestinationPath c:\etc\.; \
    Rename-Item -Force -Path c:\etc\nginx-1.21.3 -NewName nginx; \
    \
    Write-Host 'Cleaning ...'; \
    Remove-Item -Force -Path c:\nginx.zip | Out-Null; \
    \
    Write-Host 'Complete.'
COPY bin/wins.exe /Windows/wins.exe
COPY tests/integration/docker/nginx.ps1 /Windows/
ENTRYPOINT ["powershell", "-NoLogo", "-NonInteractive", "-File", "c:/Windows/nginx.ps1"]
