name: Release

on:
  push:
    tags:
      - '*'

jobs:
  create-push-image-windows-2022:
    runs-on: windows-2022
    env:
      REPO: rancher
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG: ${{ github.ref_name }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: retrieve dockerhub credentials
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD

      - name: Log in to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: 'stable'
          cache: 'false'

      - name: Install Dependencies
        run: |
          go install github.com/magefile/mage@69e6f824732575e57977f68f8f3dd78313d666e5
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@8f3b0c7ed018e57905fbd873c697e0b1ede605a5

      - name: build-binary
        run: |
          set PSModulePath=&&powershell -command "mage ci"

      # Note: We cannot use the docker/build-push-action as it requires dependencies
      # which cannot be installed onto windows VMs. Additionally, it is not possible to cross compile
      # Windows images on linux. So, we're stuck with manual docker commands.
      - name: Build Windows 2022
        run: ./scripts/build-image.ps1 -NanoServerVersion "ltsc2022" -Repo "${{ env.REPO }}" -Tag "${{ env.TAG }}"

      - name: push images
        run: |
          docker push ${{ env.REPO }}/wins:${{ env.TAG }}-windows-ltsc2022

  create-push-image-windows-2019-using-2025:
    runs-on: windows-2025
    env:
      REPO: rancher
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG: ${{ github.ref_name }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: retrieve dockerhub credentials
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD

      - name: Log in to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      # This step is required otherwise the 'mage'
      # command cannot be used in subsequent steps
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: 'stable'
          cache: 'false'

      - name: Install Dependencies
        run: |
          go install github.com/magefile/mage@69e6f824732575e57977f68f8f3dd78313d666e5
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@8f3b0c7ed018e57905fbd873c697e0b1ede605a5

      - name: build-binary
        run: |
          set PSModulePath=&&powershell -command "mage ci"

      # Note: We cannot use the docker/build-push-action as it requires dependencies
      # which cannot be installed onto windows VMs. Additionally, it is not possible to cross compile
      # Windows images on linux. So, we're stuck with manual docker commands.
      - name: Build Windows 2019
        run: ./scripts/build-image.ps1 -NanoServerVersion "ltsc2019" -Repo "${{ env.REPO }}" -Tag "${{ env.TAG }}"

      - name: push images
        run: |
          docker push ${{ env.REPO }}/wins:${{ env.TAG }}-windows-ltsc2019

  create-draft:
    runs-on: ubuntu-latest
    needs:
    - create-push-image-windows-2022
    - create-push-image-windows-2019-using-2025
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Create draft release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create -R "${GITHUB_REPOSITORY}" --draft --generate-notes "${GITHUB_REF_NAME}"

  build-binaries:
    needs: [ create-draft, create-push-image-windows-2019-using-2025, create-push-image-windows-2022 ]
    runs-on: windows-2022
    permissions:
      contents: write # required for writing release artifacts
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: 'stable'

      - name: Install Dependencies
        run: |
          go install github.com/magefile/mage@69e6f824732575e57977f68f8f3dd78313d666e5
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@8f3b0c7ed018e57905fbd873c697e0b1ede605a5

      - name: build-binary
        run: |
          set PSModulePath=&&powershell -command "mage buildAll"

      - name: Upload release artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: release-artifacts
          path: |
            artifacts/wins.exe
            artifacts/sha256.txt
            artifacts/sha512.txt
            LICENSE
          if-no-files-found: error

  create-manifest:
    needs: [ create-push-image-windows-2019-using-2025, create-push-image-windows-2022 ]
    permissions:
      id-token: write
    env:
      REPO: rancher
      TAG: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: retrieve dockerhub credentials
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD

      - name: Log in to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: create manifest list
        run: |
          docker manifest create ${{ env.REPO }}/wins:${{ env.TAG }} ${{ env.REPO }}/wins:${{ env.TAG }}-windows-ltsc2022 ${{ env.REPO }}/wins:${{ env.TAG }}-windows-ltsc2019
          docker manifest push ${{ env.REPO }}/wins:${{ env.TAG }}

  finalize-github-release:
    name: Publish GitHub release
    needs: [ build-binaries, create-manifest ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: release-artifacts
          path: /tmp/assets

      - name: Upload assets to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload -R "${GITHUB_REPOSITORY}" "${GITHUB_REF_NAME}" /tmp/assets/artifacts/* /tmp/assets/LICENSE

      - name: Publish the release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FLAGS="--draft=false"
          if [[ "${GITHUB_REF_NAME}" == *"-rc"* ]]; then
            FLAGS="${FLAGS} --prerelease"
          fi
          gh release edit -R "${GITHUB_REPOSITORY}" "${GITHUB_REF_NAME}" ${FLAGS}
